CI Test
Signed-off-by: Hendrix-Shen <HendrixShen@hendrixshen.top>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -40,12 +40,77 @@ jobs:
           commit_count=$(git log | grep -e '^commit [a-zA-Z0-9]*' | wc -l)
           echo "short_sha=$short_sha" >> $GITHUB_OUTPUT
           echo "commit_count=$commit_count" >> $GITHUB_OUTPUT
+      - name: Get github release information
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        id: get_release
+        uses: cardinalby/git-get-release-action@1.2.4
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        with:
+          tag: ${{ github.event.inputs.publish_target_release_tag }}
       - name: Read Properties mod info
         id: mod_info
         uses: christian-draeger/read-properties@1.1.1
         with:
           path: gradle.properties
           properties: 'mod.name mod.version'
+      - name: Prepare file information
+        id: file_info
+        run: |
+          shopt -s extglob
+          FILE_PATHS=$(ls ${{ format('build-artifacts/magiclib-wrapper/{0}/{1}/build/libs/!(*-@(dev|sources|shadow|javadoc|empty)).jar', inputs.publish_platform, inputs.publish_mc_ver) }})
+          
+          if (( ${#FILE_PATHS[@]} != 1 )); then
+              echo "Error: Found ${#FILE_PATHS[@]} files, expected exactly 1"
+              exit 1
+          else
+              FILE_PATH=${FILE_PATHS[0]}
+          fi
+          
+          FILE_NAME=$(basename $FILE_PATH)
+          FILE_HASH=$(sha256sum $FILE_PATH | awk '{ print $1 }')
+          echo "path=$FILE_PATH" >> $GITHUB_OUTPUT
+          echo "name=$FILE_NAME" >> $GITHUB_OUTPUT
+          echo "hash=$FILE_HASH" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+      - name: Prepare changelog (Dev Channel)
+        if: ${{ inputs.publish_channel == 'dev' }}
+        uses: actions/github-script@v6
+        id: changelog_dev
+        with:
+          script: return process.env.CHANGELOG
+          result-encoding: string
+        env:
+          CHANGELOG: |-
+            **This version is automatically released by CI Build**
+            Latest commit log:
+            ${{ github.event.head_commit.message }}
+            
+            -------
+            
+            Build Information
+            
+            - File name: `${{ steps.file_info.outputs.name }}`
+            - SHA-256: `${{ steps.file_info.outputs.hash }}`
+            - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      - name: Prepare changelog (Stable Channel)
+        if: ${{ inputs.publish_channel == 'stable' }}
+        uses: actions/github-script@v6
+        id: changelog_release
+        with:
+          script: return process.env.CHANGELOG
+          result-encoding: string
+        env:
+          CHANGELOG: |-
+            ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
+            
+            -------
+            
+            Build Information
+            
+            - File name: `${{ steps.file_info.outputs.name }}`
+            - SHA-256: `${{ steps.file_info.outputs.hash }}`
+            - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
       - name: Publish Minecraft Mods (Dev Channel)
         if: ${{ inputs.publish_channel == 'dev' }}
         uses: Kir-Antipov/mc-publish@v3.3
@@ -70,10 +135,8 @@ jobs:
           name: '[CI#${{ github.run_number }}]${{ steps.mod_info.outputs.mod-name }} ${{ steps.mod_info.outputs.mod-version }}.${{ steps.get_git_info.outputs.commit_count }}+${{ steps.get_git_info.outputs.short_sha }}'
           version: ${{ steps.mod_info.outputs.mod-version }}.${{ steps.get_git_info.outputs.commit_count }}+${{ steps.get_git_info.outputs.short_sha }}
           version-type: alpha
-          changelog: |
-            **This version is automatically released by CI Build**
-            Latest commit log:
-            ${{ github.event.head_commit.message }}
+          modrinth-changelog: ${{ steps.changelog_dev.outputs.result }}
+          curseforge-changelog: ${{ steps.changelog_dev.outputs.result }}
           loaders: |
             ${{ inputs.publish_platform }}
           game-versions: |
@@ -107,7 +170,9 @@ jobs:
           name: '${{ steps.mod_info.outputs.mod-name }} ${{ steps.mod_info.outputs.mod-version }}.${{ steps.get_git_info.outputs.commit_count }}+${{ steps.get_git_info.outputs.short_sha }}'
           version: ${{ steps.mod_info.outputs.mod-version }}.${{ steps.get_git_info.outputs.commit_count }}
           version-type: release
-          changelog: ${{ github.event.release.body }}
+          github-changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
+          modrinth-changelog: ${{ steps.changelog.outputs.result }}
+          curseforge-changelog: ${{ steps.changelog.outputs.result }}
           loaders: |
             ${{ inputs.publish_platform }}
           game-versions: |
